sudo: required
services:
  - docker

before_install:
  - docker build -t jonricaurte/docker-react -f Dockerfile.dev .

script:
  - docker run jonricaurte/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-168452182586'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    # prettier-ignore
    secure: "$AWS_SECRET_KEY"
